---
training:
  fold_count: 10
  epoch_count: 100
  batch_size: 32
  learning_rate: 1.0e-2
  weight_decay: 1.0e-3
  patience: 5

# tsne:
#   perplexity: 30
#   early_exaggeration: 12
#   learning_rate: 100
#   max_iter: 1000
#   n_iter_without_progress: 500

...